### ISSUE TITLE
完全按照步骤来，最后无法连接数据库

### ISSUE THREAD

**Issue by ayanami-desu** [KodCloud-dev/docker#11]
`DbMysqli->connect();
Host '172.25.0.3' is not allowed to connect to this MariaDB server`

**Comment by ayanami-desu** [comment]
设备是斐讯n1,openwrt系统

**Comment by KodCloud-dev** [comment]
按什么步骤？这个提示是数据库权限问题

**Comment by ayanami-desu** [comment]
拉取仓库代码，填入数据库root密码，然后docker-compose启动容器，进入页面后，直接显示的是第三步（设置管理员密码）。
我注释掉kod容器与数据库有关的环境变量后，再次启动容器，这时需要手动填入数据库名称、用户名等信息，这种情况下能正常使用。

KodCloud-dev ***@***.***> 于2022年5月16日周一 11:17写道：
