### ISSUE TITLE
compose文件环境变量有误

### ISSUE THREAD

**Issue by KOPElan** [KodCloud-dev/docker#21]
yml文件中数据库环境变量名称有误，MYSQL_HOST应该为：MYSQL_SERVER
>
 >app:
>    image: kodcloud/kodbox
>    restart: always
>    ports:
>      - 80:80                       #左边80是使用端口，可以修改
>    volumes:
>      - "./site:/var/www/html"      #./site是站点目录位置，可以修改
>    environment:
>      - MYSQL_HOST=db
>      - REDIS_HOST=redis

**Comment by KodCloud-dev** [comment]
没问题，容器有更新，最新版本正在构建，或拉取`kodcloud/kodbox:1.49.01`
