### ISSUE TITLE
部署完后，打开kodbox，提示数据表缺失或异常

### ISSUE THREAD

**Issue by PavelKorchagine** [KodCloud-dev/docker#25]
部署完后，打开kodbox，提示数据表缺失或异常

**Comment by PavelKorchagine** [comment]
![image](https://github.com/user-attachments/assets/5073b669-9cee-4119-a04d-3dcfec204c5f)

**Comment by KodCloud-dev** [comment]
可以先拉取使用`kodcloud/kodbox:1.52`, latest版本等下更新
