### ISSUE TITLE
树莓派运行出错

### ISSUE THREAD

**Issue by airfx** [KodCloud-dev/docker#3]
运行
docker run -d --name kodbox -p 619:80 kodcloud/kodbox

树莓派环境
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

docker=20.10.8, build 3967b7d
python=Python 2.7.16

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : d03114
Serial          : 100000005d2c9da4
Model           : Raspberry Pi 4 Model B Rev 1.4

错误日志：
KODBOX is installing ...,
Fatal Python error: init_interp_main: can't initialize time,
Python runtime state: core initialized,
PermissionError: [Errno 1] Operation not permitted,
,
Current thread 0xb6f5f390 (most recent call first):,
<no Python frame>

**Comment by KodCloud-dev** [comment]
[参考这里](https://community.home-assistant.io/t/migration-to-2021-7-fails-fatal-python-error-init-interp-main-cant-initialize-time/320648/8 )看下 
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```

**Comment by airfx** [comment]
kodbox yes! 
`sudo apt install -t buster-backports libseccomp2`
完美解决
