### ISSUE TITLE
暗黑主题下，跟随壁纸功能无效。

### ISSUE THREAD

**Issue by airfx** [KodCloud-dev/docker#4]
![image](https://user-images.githubusercontent.com/37166707/130164156-9d8d89fd-a1a1-488e-adf0-67576668ab03.png)
暗黑主题下，跟随壁纸功能无效。貌似壁纸被写死在样式里，要是可以变化而且模糊，那就完美。

**Comment by KodCloud-dev** [comment]
请到[可道云论坛](https://bbs.kodcloud.com/)反馈问题
