### ISSUE TITLE
PHP拓展

### ISSUE THREAD

**Issue by yingwuxi** [KodCloud-dev/docker#6]
您好，博主，请问您的docker版可道云，怎么安装Swoole拓展呢？非常感谢您了！
![image](https://user-images.githubusercontent.com/58382753/145833128-552f69cf-afc4-43bc-acb1-b12064a89013.png)

**Comment by KodCloud-dev** [comment]
5600439
影响arm版镜像打包所以拿掉了，目前没有影响因为实际上没有用到该扩展
