### ISSUE TITLE
修改容器用户

### ISSUE THREAD

**Issue by CaimFxp** [KodCloud-dev/docker#7]
我管理文件使用的用户不是root，如何修改容器的用户？

**Comment by KodCloud-dev** [comment]
你的意思是像LinuxServer提供的容器那样通过环境变量的方式来修改UID和GID吗

**Comment by CoolLoong** [comment]
> 你的意思是像LinuxServer提供的容器那样通过环境变量的方式来修改UID和GID吗

没错，我也需要这个功能。因为我的容器全部设置的与宿主机用户相同，都是uid=1024 gid=100，需要修改容器用户，达到权限统一

**Comment by KodCloud-dev** [comment]
kodcloud/kodbox:v1.28 已支持，请在运行时加上 `-e PUID=1024 -e PGID=100`

**Comment by CoolLoong** [comment]
> kodcloud/kodbox:v1.28 已支持，请在运行时加上 `-e PUID=1024 -e PGID=100`

创建容器时deluser nginx报错，在群辉系统上设置-e PUID=1024 -e PGID=100出现
