### ISSUE TITLE
compose部署出错

### ISSUE THREAD

**Issue by john2021wick** [KodCloud-dev/docker#9]
按照教程
git clone https://github.com/KodCloud-dev/docker.git kodbox
cd ./kodbox/compose/
修改docker-compose.yaml，设置数据库root密码（MYSQL_ROOT_PASSWORD=密码）
docker-compose up -d

app容器的状态一直在restarting，查看日志：
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set
app_1    | /entrypoint.sh: line 80: PUID: parameter not set

**Comment by KodCloud-dev** [comment]
请重新执行 `docker pull kodcloud/kodbox:v1.28`再试下
